version: "3.4"
services:
  devcontainer:
    container_name: frigate-devcontainer
    privileged: true
    restart: unless-stopped
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: frigate
      # Use target devcontainer-trt for TensorRT dev
    ## Uncomment this block for nvidia gpu support
    # deploy:
    #       resources:
    #           reservations:
    #               devices:
    #                   - driver: nvidia
    #                     count: 1
    #                     capabilities: [gpu]
    environment:
      YOLO_MODELS: yolov7-320
      IPCAMERA_PASSWORD: Si1neHas10
      IPCAMERA_LOGIN: admin
      HOST_ADDRESS: 192.168.1.31
      POSTGES_ADDRESS: 192.168.8.124
      POSTGRES_PORT: 5434
      REMOTE_STORAGE_ADDRESS: 192.168.8.124
      REMOTE_STORAGE_HOST: 9001
      REMOTE_STORAGE_ACCESS_KEY: minioadmin
      REMOTE_STORAGE_SECRET_KEY: minioadmin
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
        #- ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.coral.yml:/config/config.yml
      - /mnt/usbdrive:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
    #  - /home/mvision/apps/deps/go2rtc:/config/go2rtc
    #  - /home/kamil/praca/mebaya/misc/go2rtc/go2rtc:/config/go2rtc
